{
 "title": "Example service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage - Gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "stat_cpu_usage:percent{app=\"exampleService\",env=\"test\"}"
    }
   ]
  },
  {
   "title": "CPU Usage - Timeline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stat_cpu_usage:percent{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Handler 1 - Response SIze - Gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "response_size{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}"
    }
   ]
  },
  {
   "title": "Handler 1 - Response SIze - Timeline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_size{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "Handler 2 - Response SIze - Gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "response_size{app=\"exampleService\",env=\"test\",handler=\"MyHandler2\"}"
    }
   ]
  },
  {
   "title": "Handler 2 - Response SIze - Timeline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_size{app=\"exampleService\",env=\"test\",handler=\"MyHandler2\"}",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "Service Goroutines - Gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "stat_goroutines:count{app=\"exampleService\",env=\"test\"} "
    }
   ]
  },
  {
   "title": "Service Goroutines - Timeline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stat_goroutines:count{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "Goroutines Count"
    }
   ]
  },
  {
   "title": "Used memory (System)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:used_percent{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "vm total"
    }
   ]
  },
  {
   "title": "Free memory (System)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - stat_memory_usage:used_percent{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "free memory"
    }
   ]
  },
  {
   "title": "Memory: sys (Application)",
   "type": "singlestat",
   "description": "Sys is the total bytes of memory obtained from the OS",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:sys{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app sys"
    }
   ]
  },
  {
   "title": "Memory: alloc (Application)",
   "type": "singlestat",
   "description": "Alloc is bytes of allocated heap objects",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:alloc{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app alloc"
    }
   ]
  },
  {
   "title": "Memory: heapsys (Application)",
   "type": "singlestat",
   "description": " HeapSys is bytes of heap memory obtained from the OS",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 23 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:heapsys{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app heapsys"
    }
   ]
  },
  {
   "title": "Memory: heapinuse (Application)",
   "type": "singlestat",
   "description": "HeapInuse is bytes in in-use spans",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:heapinuse{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app heapinuse"
    }
   ]
  },
  {
   "title": "Memory: frees (Application)",
   "type": "singlestat",
   "description": "Frees is the cumulative count of heap objects freed",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:frees{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app frees"
    }
   ]
  },
  {
   "title": "Memory: numgc (Application)",
   "type": "singlestat",
   "description": " NumGC is the number of completed GC cycles",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stat_memory_usage:numgc{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "app numgc"
    }
   ]
  },
  {
   "title": "execution_time:nano_sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        execution_time:nano_sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[1m]\n    )\n) ",
     "legendFormat": "execution time"
    }
   ]
  },
  {
   "title": "execution_time:micro_sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        execution_time:micro_sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[1m]\n    )\n) ",
     "legendFormat": "execution time"
    }
   ]
  },
  {
   "title": "execution_time:milli_sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        execution_time:milli_sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[5m]\n    )\n) ",
     "legendFormat": "execution time"
    }
   ]
  },
  {
   "title": "execution_time:seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n      execution_time:seconds_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[5m]\n    ) \n) ",
     "legendFormat": "execution time"
    }
   ]
  },
  {
   "title": "execution_time:minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n      execution_time:minutes_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[5m]\n    ) \n) ",
     "legendFormat": "execution time"
    }
   ]
  },
  {
   "title": "Handler 1 Response Time (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        response_time:sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[1m]\n    )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Handler 2 Response Time (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        response_time:milli_sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler2\"}[5m]\n    )\n) ",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response Times of Handlers (AVG / Comparison)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        response_time:sec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[5m]\n    )\n)",
     "legendFormat": "Handler 1"
    },
    {
     "expr": "histogram_quantile(0.9,\n    rate(\n        response_time:millisec_bucket{app=\"exampleService\",env=\"test\",handler=\"MyHandler2\"}[5m]\n    )\n) ",
     "legendFormat": "Handler2"
    }
   ]
  },
  {
   "title": "Memory Usage (System)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "stat_memory_usage:total{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "vm total"
    },
    {
     "expr": "stat_memory_usage:avail{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "vm avail"
    },
    {
     "expr": "stat_memory_usage:used{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "vm used"
    },
    {
     "expr": "stat_memory_usage:free{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "vm free"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "stat_cpu_usage:percent{app=\"exampleService\",env=\"test\"}",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Pie Chart - Status codes of MyHandler1",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "response_status{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}\n",
     "legendFormat": "{{statuscode}}"
    }
   ]
  },
  {
   "title": "Timeline - Status codes of MyHandler1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    response_status{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}[5m]\n  )\n) by(statuscode)\n",
     "legendFormat": "{{statuscode}}"
    }
   ]
  },
  {
   "title": "Pie Chart - Status codes of MyHandler2",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "response_status{app=\"exampleService\",env=\"test\",handler=\"MyHandler1\"}\n",
     "legendFormat": "{{statuscode}}"
    }
   ]
  },
  {
   "title": "Timeline - Status codes of MyHandler2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    response_status{app=\"exampleService\",env=\"test\",handler=\"MyHandler2\"}[5m]\n  )\n) by(statuscode)\n",
     "legendFormat": "{{statuscode}}"
    }
   ]
  }
 ]
}